version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: book_my_ticket_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sql_class_2_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/001_users_and_seats.sql:/docker-entrypoint-initdb.d/001_users_and_seats.sql

volumes:
  postgres_data:
